/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutProductSection: typeof import('./src/components/AboutProductSection.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BrandTimeline: typeof import('./src/components/BrandTimeline.vue')['default']
    FaqBody: typeof import('./src/components/FaqBody.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ReviewForm: typeof import('./src/components/ReviewForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreDetailBody: typeof import('./src/components/StoreDetailBody.vue')['default']
    TraceBoard: typeof import('./src/components/TraceBoard.vue')['default']
    TraceInfoBlock: typeof import('./src/components/TraceInfoBlock.vue')['default']
  }
}
